name: on-demand-load-test

on:
  workflow_dispatch:

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-interaction --no-root
          pip install locust

      - name: Run Locust load test (headless)
        env:
          STAGING_BASE_URL: ${{ secrets.STAGING_BASE_URL }}
        run: |
          locust -f load/semantic_search.py --headless -u 200 -r 20 -t 5m --host "$STAGING_BASE_URL" | cat 